### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-invoice-reporting#240]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] account_comment_template - By @Yadier-Tecnativa - #274
- [ ] account_invoice_line_sale_line_position
- [ ] account_invoice_report_due_list - By @dsolanki-initos - #282
- [x] account_invoice_report_payment_info - By @stefan-tecnativa - #270
- [x] account_reporting_volume - By @stefan-tecnativa - #284
- [x] account_reporting_weight - By @Yadier-Tecnativa - #272

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by ferran-S73** [comment]
account_invoice_report_grouped_by_picking: https://github.com/OCA/account-invoice-reporting/pull/256

**Comment by RodrigoBM** [comment]
Im working on account_invoice_report_due_list

**Comment by ferran-S73** [comment]
> Im working on account_invoice_report_due_list

@RodrigoBM is this module still needed? You might want to check [the base report in v16](https://github.com/odoo/odoo/blob/7d8e3d8472c0c87ca0b789142cc7ec8b6fd3c51f/addons/account/views/report_invoice.xml#L211) since Odoo added a similiar feature.

cc @OCA/accounting-maintainers

**Comment by RodrigoBM** [comment]
@ferran-S73 , I'll check this out, thanks

**Comment by BT-anieto** [comment]
I'm missing account_invoice_production_lot in the list

**Comment by David-Luis-Mora** [comment]
account_invoice_line_sale_line_position :  #310
