### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-invoice-reporting#41]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] html_invoice_product_note
- [ ] invoice_print_report_balance_payment
- [ ] account_invoice_production_lot
- [ ] invoice_webkit
- [ ] account_invoice_delivery_address
- [x] account_draft_invoice_print @vrenaville 
- [ ] invoice_report_assemble
- [x] invoice_comment_template https://github.com/OCA/account-invoice-reporting/pull/46
- [x] base_comment_template https://github.com/OCA/account-invoice-reporting/pull/46

**Comment by vrenaville** [comment]
@yvaucher I will make a PR for removing account_draft_invoice_print , in V9 you can print the invoice 
with the menu "Print"

**Comment by vrenaville** [comment]
@yvaucher , finally I will migrate it, button is definitively required. sorry for noise

**Comment by yvaucher** [comment]
@vrenaville I added you in the list
