### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-invoice-reporting#48]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] account_draft_invoice_print - @bodedra - #54 
- [x] ~~account_invoice_delivery_address~~: feature provided by core
- [x] account_invoice_line_report - By @binhlam - #74 
- [x] account_invoice_production_lot - By @cubells - #61 
- [x] account_invoice_report_by_partner - By @cubells - #56 
- [x] base_comment_template - By @SimoRubi  - #65 
- [ ] html_invoice_product_note
- [x] invoice_comment_template - By @clb-openfire - #65 
- [ ] invoice_print_report_balance_payment
- [ ] invoice_report_assemble
- [ ] invoice_webkit

**Comment by bodedra** [comment]
@pedrobaeza _account_invoice_delivery_address_ module functionality already available in Odoo10.

_sale_ module added _partner_shipping_id_ in account.invoice object and Invoice report looks good with shipping address.

Following are reference link of source code.

[.py file reference](https://github.com/odoo/odoo/blob/10.0/addons/sale/models/account_invoice.py#L22)
[.xml report file reference](https://github.com/odoo/odoo/blob/10.0/addons/sale/report/invoice_report_templates.xml#L75)

Looking forward with your suggestion.

**Comment by SimoRubi** [comment]
Hi, I've fixed PR #57 (and #64) with #65 for base_comment_template and invoice_comment_template

**Comment by binhlam** [comment]
Hi, I will migrate module `account_invoice_line_report` from v9.0 to v10.0.

**Comment by pedrobaeza** [comment]
Great, check that the module is being migrated to v11 in #69.
