### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-invoice-reporting#63]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] account_draft_invoice_print
- [x] account_invoice_line_report - By @cubells - #69 
- [x] account_invoice_production_lot - By @pedrobaeza - #95
- [ ] account_invoice_report_by_partner
- [x] account_invoice_report_due_list - By @cubells - #94 
- [x] account_reporting_weight - By @chienandalu - #90 
- [x] base_comment_template - By @xavierjimenez - #80 
- [ ] html_invoice_product_note
- [x] invoice_comment_template > account_invoice_comment_template - By @xavierjimenez - #81 
- [ ] invoice_print_report_balance_payment
- [ ] invoice_report_assemble
- [ ] invoice_webkit
- [x] partner_time_to_pay by @max3903 in #67

**Comment by pedrobaeza** [comment]
Migrating `account_invoice_production_lot`

**Comment by emagdalenaC2i** [comment]
@pedrobaeza Please add to the list invoice_comment_template that is renamed as account_invoice_comment_template and merged in #81 
add to the list account_invoice_report_due_list that is migrated and merged in #94
